//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Surface.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SURFACE_FORM                101
#define IDR_MAINFRAME                   128
#define IDR_SURFACTYPE                  129
#define IDD_OPTION                      130
#define IDC_CURSOR1                     131
#define IDD_RESULT                      131
#define IDD_ORDERS                      132
#define IDD_DLG_BASE                    133
#define IDI_ICON2                       157
#define IDI_ICON1                       158
#define IDI_ICON3                       159
#define IDI_ICON4                       160
#define IDI_ICON5                       161
#define IDI_ICON6                       162
#define IDI_ICON7                       163
#define IDI_ICON8                       164
#define IDI_ICON9                       165
#define IDI_ICON10                      166
#define IDI_ICON11                      167
#define IDC_CANCEL                      1000
#define IDC_BEGIN                       1001
#define IDC_OPTION                      1002
#define IDC_EDIT_Coverage_Percent       1003
#define IDC_EDIT_Raft_Coverage_Percent  1003
#define IDC_EDIT_Ppob_SynSNAP25_Dis     1003
#define IDC_EDIT_Diffusion_Coefficient  1004
#define IDC_EDIT7                       1005
#define IDC_EDIT_Cur_Ag_Number          1005
#define IDC_EDIT_Ppob_SntSnt_Dis        1005
#define IDC_EDIT_Diffusion_Coefficient_in_Raft 1006
#define IDC_EDIT_Vamp_D                 1006
#define IDC_DINAMIC                     1007
#define IDC_EDIT_D_ESF                  1007
#define IDC_EDIT_Dffusion_Coefficient_from_Raft 1008
#define IDC_EDIT_Stx_D                  1008
#define IDC_EDIT_PercentRecInRaft       1009
#define IDC_EDIT_Raft_coverage          1009
#define IDC_EDIT_Raft_number            1009
#define IDC_EDIT_CurDrafNumber          1010
#define IDC_EDIT_CurRaftNumber          1010
#define IDC_EDIT_initStxNumber          1010
#define IDC_EDIT8                       1011
#define IDC_EDIT_Simulation_Duration    1011
#define IDC_EDIT_initSNAP25Number       1011
#define IDC_CANCEL_OPT                  1012
#define IDC_EDIT_initNSFNumber          1012
#define IDC_EDIT_TO_ENTER_INTO_THE_RAFT 1013
#define IDC_EDIT_Ppob_Snt_bind_SNAP25   1013
#define IDC_EDIT_REC_NUM                1014
#define IDC_EDIT_initVampNumber         1014
#define IDC_EDITDRAF_NUM                1015
#define IDC_EDIT_StxPout_raft           1015
#define IDC_Coverage_Percent            1016
#define IDC_Raft_Coverage_Percent       1016
#define IDC_Ppob_SynSNAP25_Dis          1016
#define IDC_Diffusion_Coefficient       1017
#define IDC_Dffusion_Coefficient_from_Raft 1018
#define IDC_STATIC_Diffusion_Coefficient_in_Raft 1019
#define IDC_STATIC_D_Vamp               1019
#define IDC_TO_ENTER_INTO_THE_RAFT      1020
#define IDC_Ppob_Snt_bind_SNAP25        1020
#define IDC_PROBABILITY_TO_LEAVE_RAFT   1021
#define IDC_Ppob_Snt_SNAP25_bind_Vamp   1021
#define IDC_EDIT_PROBABILITY_TO_LEAVE_RAFT 1022
#define IDC_EDIT_Ppob_Snt_SNAP25_bind_Vamp 1022
#define IDC_REC_NUM                     1023
#define IDC_STATIC_D_ESF                1023
#define IDC_DRAF_NUM                    1024
#define IDC_STATIC_Raft_coverage        1024
#define IDC_STATIC_Raft_number          1024
#define IDC_STEP                        1025
#define IDC_STATIC_initStxNumber        1025
#define IDC_EDITD_STEP                  1026
#define IDC_STATIC_initSNAP25Number     1026
#define IDC_STEPS                       1027
#define IDC_STATIC_initVampNumber3      1027
#define IDC_EDITD_STEPS                 1028
#define IDC_STATIC_StxPin_raft          1028
#define IDC_PercentRecInRaft            1029
#define IDC_STEPS2                      1029
#define IDC_STATIC_initNSFNumber        1029
#define IDC_DRAW                        1030
#define IDC_STATIC_SNAP25Pin_raft       1030
#define IDC_PROBABILITY2                1031
#define IDC_EDIT_SNAP25Pout_raft        1031
#define IDC_EDIT_PROBABILITY_TO_LEAVE_RAFT2 1032
#define IDC_EDIT_UpdateWindowVariable   1032
#define IDC_STATIC_NSFPin_raft          1032
#define IDC_STATIC_D_ESF3               1032
#define IDC_PROBABILITY_TO_LEAVE_RAFT3  1033
#define IDC_RAFT_PROBABILITY_TO_MERGE   1033
#define IDC_PROBABILITY_NSF_ACT         1033
#define IDC_P_NSF_on_Snt_Snap           1033
#define IDC_EDIT_PROBABILITY_TO_LEAVE_RAFT3 1034
#define IDC_EDIT_RAFT_PROBABILITY_TO_MERGE 1034
#define IDC_EDIT_PROBABILITY_NSF_ACT    1034
#define IDC_EDIT_P_NSF_on_Snt_Snap      1034
#define IDC_PROBABILITY_TO_LEAVE_RAFT4  1035
#define IDC_R_Prob_to_Bind_AG           1035
#define IDC_EDIT_PROBABILITY_TO_LEAVE_RAFT4 1036
#define IDC_EDIT_Probability_to_Bind_Ag 1036
#define IDC_EDIT_Snap25_D               1036
#define IDC_CurDrafNumber               1037
#define IDC_CurRaftNumber               1037
#define IDC_EDIT_NSFPout_raft           1037
#define IDC_EDIT_D_Alpha                1037
#define IDC_EDIT9                       1038
#define IDC_STEPS3                      1038
#define IDC_STATIC_VampPin_raft         1038
#define IDC_R_Prob_to_Unbind_AG         1039
#define IDC_Ppob_Snt_SNAP25_Vamp_Dissociation 1039
#define IDC_EDIT_Probability_to_Unbind_from_Ag 1040
#define IDC_EDIT_Ppob_SynSNAP25VAMP_Dis 1040
#define IDC_Ag_Number_per_Time_Step     1041
#define IDC_Ppob_SntSNAP25_BindSnt      1041
#define IDC_Ppob_SntSNAP25Vamp_BindAlpha 1041
#define IDC_EDIT_Ag_number_per_Time_Step 1042
#define IDC_EDIT_Ppob_SynSNAP25_BindSnt 1042
#define IDC_EDIT_Ppob_SynSNAPVamp_BindAlpha 1042
#define IDC_Hapten_Number_per_Ag        1043
#define IDC_Ag_Habten_Density           1043
#define IDC_Ppob_Snt_SNAP25Snt_Dis      1043
#define IDC_Ppob_Snt_SNAP25VampAlpha_Dis 1043
#define IDC_EDIT_Hapten_Number_per_Ag   1044
#define IDC_EDIT_Ag_Habten_Density      1044
#define IDC_EDIT_Ppob_SntSNAP25Snt_Dis  1044
#define IDC_EDIT_Ppob_SntSNAP25VampAlpha_Dis 1044
#define IDC_Cur_Ag_Number               1045
#define IDC_EDIT_VampPout_raft          1045
#define IDC_TimerInitialisator          1046
#define IDC_STATIC_StxPout_raft         1046
#define IDC_EDIT_TimerInitialisator     1047
#define IDC_EDIT_StxPin_raft            1047
#define IDC_Simulation_Duration         1048
#define IDC_STATIC_SNAP25Pout_raft      1048
#define IDC_Dffusion_Coefficient_from_Raft2 1049
#define IDC_EDIT_SNAP25Pin_raft         1049
#define IDC_EDIT_ZOOM                   1050
#define IDC_STATIC_NSFPout_raft         1050
#define IDC_STATIC_LifeTime_NSF         1050
#define IDC_Draw_Rec_Indexes            1051
#define IDC_PROBABILITY3                1051
#define IDC_EDIT_NSFPin_raft            1051
#define IDC_EDIT_LifeTime_NSF           1051
#define IDC_Dffusion_Coefficient_from_Raft3 1052
#define IDC_STATIC_VampPout_raft        1052
#define IDC_STATIC_GRID_SZ              1053
#define IDC_EDIT_VampPin_raft           1053
#define IDC_STATIC_GRID_SZ2             1054
#define IDC_STATIC_initStxInRaftFract   1054
#define IDC_NEXT_STEP                   1055
#define IDC_EDIT_initStxInRaftFract     1055
#define IDC_CHECK_STEP                  1056
#define IDC_STATIC_initSNAP25InRaftFract 1056
#define IDC_COMBO_ZOOM                  1057
#define IDC_EDIT_initSNAP25InRaftFract  1057
#define IDC_CHEK_Draw_Indexes           1058
#define IDC_STATIC_initNSFInRaftFract   1058
#define IDC_EDIT_Win_Update_Timer       1059
#define IDC_EDIT_initNSFInRaftFract     1059
#define IDC_CHEK_Draw_Molec             1060
#define IDC_CHEK_Draw_SM_names          1060
#define IDC_TAB_CNTRL                   1060
#define IDC_STATIC_initVampInRaftFract  1060
#define IDC_CHEK_Draw_Names             1061
#define IDC_EDIT_initVampInRaftFract    1061
#define IDC_Snt_SNAP25_Pin_raft         1062
#define IDC_CHEK_Draw_Rec               1063
#define IDC_TAB                         1063
#define IDC_EDIT_Snt_SNAP25_Pin_raft    1063
#define IDC_CHEK_Draw_SM                1064
#define IDC_OK                          1064
#define IDC_CHEK_Draw_Ag_Indexes        1065
#define IDC_Snt_SNAP25_Vamp_Pin_raft    1065
#define IDC_CHEK_Draw_Ag                1066
#define IDC_EDIT_Snt_SNAP25_Vamp_Pin_raft 1066
#define IDC_CHEK_Draw_SM_Ind            1067
#define IDC_SntSNAP25_Snt_Pin_raft      1067
#define IDC_SntSNAP25_Vamp_Alpha_Pin_raft 1067
#define IDC_CHEK_Draw_Raft              1068
#define IDC_IMAGE3                      1068
#define IDC_EDIT_SntSNAP25_Snt_Pin_raft 1068
#define IDC_EDIT_SntSNAP_VampAlpha_Pin_raft 1068
#define IDC_CHEK_Draw_Raft_Ind          1069
#define IDC_IMAGE4                      1069
#define IDC_Snt_SNAP25_Pout_raft2       1069
#define IDC_CHEK_Draw_Ht_Indexes        1070
#define IDC_IMAGE5                      1070
#define IDC_EDIT_Snt_SNAP25_Pout_raft   1070
#define IDC_IMAGE6                      1071
#define IDC_Snt_SNAP25_Vamp_Pout_raft2  1071
#define IDC_IMAGE7                      1072
#define IDC_EDIT_Snt_SNAP25_Vamp_Pout_raft 1072
#define IDC_IMAGE8                      1073
#define IDC_SntSNAP25_Snt_Pout_raft2    1073
#define IDC_SntSNAP25_VampAlpha_Pout_raft 1073
#define IDC_IMAGE9                      1074
#define IDC_EDIT_SntSNAP25_Snt_Pout_raft 1074
#define IDC_EDIT_SntSNAP_VampAlpha_Pout_raft 1074
#define IDC_IMAGE10                     1075
#define IDC_STATIC_Raft_size            1075
#define IDC_STATIC_freeBCR              1076
#define IDC_EDIT_MeanRaftSize           1076
#define IDC_STATIC_1armBCR              1077
#define IDC_P_NSF_on_Snt_Snap_Vamp      1077
#define IDC_CHECK_NSFtoRemoveCompl      1077
#define IDC_STATIC__1arm_A_BCR          1078
#define IDC_EDIT_P_NSF_on_Snt_Snap_Vamp 1078
#define IDC_Ppob_Snt_bind_Snt           1078
#define IDC_STATIC_2armBCR              1079
#define IDC_STATIC_D_Vamp2              1079
#define IDC_STATIC__2arm_A_BCR          1080
#define IDC_EDIT_Vamp_D_inRaft          1080
#define IDC_STATIC_SM                   1081
#define IDC_Dffusion_Coefficient_from_Raft4 1081
#define IDC_STATIC_A_SM                 1082
#define IDC_EDIT_Stx_D_inRaft           1082
#define IDC_STATIC_Ligand               1083
#define IDC_R_Prob_to_Bind_AG2          1083
#define IDC_STATIC_Raft                 1084
#define IDC_EDIT_StepsNumber            1084
#define IDC_STATIC_ActiveLyn            1085
#define IDC_STATIC_StepsNumber          1085
#define IDC_STATIC_InactiveFyn          1086
#define IDC_EDIT_Snap25_D_inRaft        1086
#define IDC_STATIC_D_ESF2               1087
#define IDC_STATIC_LifeTime_Alpha       1087
#define IDC_EDIT_D_ESF_inRaft           1088
#define IDC_EDIT_LifeTime_Alpha         1088
#define IDC_STATIC_initVampNumber4      1089
#define IDC_EDIT_initSnt_Snap25Number   1090
#define IDC_STATIC_initVampInRaftFract2 1091
#define IDC_EDIT_initSnt_Snap25InRaftFract 1092
#define IDC_STATIC_initVampNumber5      1093
#define IDC_EDIT_initSnt_Snap25VampNumber 1094
#define IDC_STATIC_initVampInRaftFract3 1095
#define IDC_EDIT_initSnt_Snap25VampInRaftFract 1096
#define IDC_STATIC_initVampNumber6      1097
#define IDC_EDIT_initSnt_Snap25VampAlphaNum 1098
#define IDC_STATIC_initVampInRaftFract4 1099
#define IDC_EDIT_initSnt_Snap25VampAlphaInRaftFract 1100
#define IDC_EDIT_Ppob_Snt_bind_Snt      1101
#define IDC_Ppob_SntSnt_bind_Snt        1102
#define IDC_EDIT_Ppob_SntSnt_bind_Snt   1103
#define IDC_Ppob_SntSnt_Dis             1104
#define IDC_Ppob_SntSntSnt_Dis          1105
#define IDC_EDIT_Ppob_SntSntSnt_Dis     1106
#define IDC_SntSnt_Pin_raft             1107
#define IDC_EDIT_SntSnt_Pin_raft        1108
#define IDC_SntSntSnt_Pin_raft          1109
#define IDC_EDIT_SntSntSnt_Pin_raft     1110
#define IDC_SntSnt_Pout_raft            1111
#define IDC_EDIT_SntSnt_Pout_raft       1112
#define IDC_SntSntSnt_Pout_raft         1113
#define IDC_EDIT_SntSntSnt_Pout_raft    1114
#define IDC_STATIC_initSntSntNum        1115
#define IDC_EDIT_initSntSntNum          1116
#define IDC_STATIC_initSntSntInRaftFract 1117
#define IDC_EDIT_initSntSntInRaftFract  1118
#define IDC_STATIC_initSntSntSntNum     1119
#define IDC_EDIT_initSntSntSntNum       1120
#define IDC_STATIC_initSntSntInRaftFract2 1121
#define IDC_EDIT_initSntSntSnt_InRaftFract 1122
#define IDC_STATIC_initAlphaNum         1123
#define IDC_EDIT_initAlphaNum           1124
#define IDC_STATIC_initAlphaInRaftFract 1125
#define IDC_EDIT_initAlphaInRaftFract   1126
#define IDC_STATIC_Ptransloc_Alpha      1127
#define IDC_EDIT_Ptransloc_Alpha        1128
#define IDC_STATIC_Ptransloc_NSF        1129
#define IDC_EDIT_Ptransloc_NSF          1130

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
